version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3.6.0
    container_name: Athena-zookeeper-1
    ports:
      - 2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      Athena-network-1:
        ipv4_address: 172.28.0.6

  nifi:
    image: apache/nifi:1.11.4
    container_name: Athena-nifi-1
    ports:
      - 8080:8080
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=10 sec
    depends_on:
      - zookeeper
    volumes:
      - hdfs_env:/hdfs_env
    networks:
      Athena-network-1:
        ipv4_address: 172.28.0.5

  # /opt/bitnami/kafka/bin
  # kafka-topics.sh --list --bootstrap-server localhost:9092
  # kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic deviation_target --from-beginning
  kafka:
    image: 'bitnami/kafka:2.5.0'
    container_name: Athena-kafka-1
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper
    networks:
      Athena-network-1:
        ipv4_address: 172.28.0.7

  # sysctl -w vm.max_map_count=262144
  elastic-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: Athena-elastic-1
    environment:
      - node.name=elastic-1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=elastic-1   #,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../Athena_Data/elastic-data:/usr/share/elasticsearch/data
      - ./elastic-env/c5FMzb7ARkC1VZ7dIgNo8w:/usr/share/elasticsearch/data/nodes/0/indices/c5FMzb7ARkC1VZ7dIgNo8w
      - ./elastic-env/EYheK8VxQ6qXOxPZRwFEOQ:/usr/share/elasticsearch/data/nodes/0/indices/EYheK8VxQ6qXOxPZRwFEOQ
      - ./elastic-env/pS9NyLv6Ts6s4ld-bFQi_Q:/usr/share/elasticsearch/data/nodes/0/indices/pS9NyLv6Ts6s4ld-bFQi_Q
    ports:
      - 9200:9200
    networks:
      Athena-network-1:
        ipv4_address: 172.28.0.12
  
  kib01:
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: Athena-kibana-1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://172.28.0.12:9200
      ELASTICSEARCH_HOSTS: http://172.28.0.12:9200
    networks:
      Athena-network-1:
        ipv4_address: 172.28.0.13

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9001:9001
    volumes:
      - ../Athena_Data/hdfs-data/namenode:/hadoop/dfs/name
      - hdfs_env:/etc/hadoop
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks:
      Athena-network-1:
        ipv4_address: 172.28.0.14

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - ..Athena_Data/hdfs-data/datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      Athena-network-1:
        ipv4_address: 172.28.0.15
  
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9001 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    networks:
      Athena-network-1:
        ipv4_address: 172.28.0.16

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9001 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    networks:
      Athena-network-1:
        ipv4_address: 172.28.0.17
  
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9001 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - ../Athena_Data/hdfs-data/historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    networks:
      Athena-network-1:
        ipv4_address: 172.28.0.18
  
  portainer:
    container_name: Athena-portainer-1
    image: portainer/portainer
    ports:
     - "9000:9000"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
      Athena-network-1:
        ipv4_address: 172.28.0.19

volumes:
  hdfs_env:
  #hadoop_namenode:
  #hadoop_datanode:
  #hadoop_historyserver:

networks:
  Athena-network-1:
    driver: bridge
    ipam:
     config:
       - subnet: 172.28.0.0/16